#!/usr/bin/env python
import argparse
import asyncio
import cProfile
import io
import os
import pstats
import sys
from unittest.mock import MagicMock

os.environ["ENV_FILE"] = os.getenv("ENV_FILE", ".env.test")

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from fastapi import FastAPI
from httpx import AsyncClient, ASGITransport
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy.pool import StaticPool


from app.main import app
from app.core.config import settings
from app.core.database import Base, engine as pg_engine
from app.core.deps import get_db
from app.service.aws.bedrock_service import BedrockService
from app.models.ticket_model import PriorityEnum, StatusEnum

BedrockService.generate_description = MagicMock(
    return_value="Mocked description generated by AWS Bedrock for profiling."
)
BedrockService.summarize_ticket = MagicMock(
    return_value={
        "summary": "Mock summary of the ticket description.",
        "suggested_response": "Mock suggested response to resolve the user issue."
    }
)

async def check_postgres() -> bool:
    try:
        # Check connection with a short timeout to prevent hanging
        async with pg_engine.connect() as conn:
            await conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False

async def run_profiling_scenario(client: AsyncClient, iterations: int):
    created_ticket_ids = []

    print(f"\n[1/5] Running API health checks...")
    await client.get("/health")
    await client.get("/ready")

    print(f"[2/5] Creating {iterations} tickets...")
    for i in range(iterations):
        payload = {
            "title": f"Profiling Test Ticket #{i}",
            "priority": PriorityEnum.HIGH.value,
            "status": StatusEnum.OPEN.value
        }
        res = await client.post("/tickets/ticket", json=payload)
        if res.status_code == 201:
            data = res.json()
            created_ticket_ids.append(data["ticket"]["id"])
        else:
            print(f"Error creating ticket #{i}: {res.status_code} - {res.text}")

    print(f"[3/5] Querying and filtering tickets...")
    # List all
    await client.get("/tickets/ticket")
    # Filters
    await client.get("/tickets/ticket?status=Open")
    await client.get("/tickets/ticket?priority=High")
    await client.get("/tickets/ticket?status=Open&priority=High")
    # Individual gets
    for tid in created_ticket_ids[:20]:
        await client.get(f"/tickets/ticket/{tid}")

    print(f"[4/5] Updating and summarizing tickets...")
    # Updates
    for tid in created_ticket_ids[:20]:
        payload = {
            "status": StatusEnum.IN_PROGRESS.value,
            "priority": PriorityEnum.CRITICAL.value
        }
        await client.put(f"/tickets/ticket/{tid}", json=payload)

    # AI Summarize endpoint calls
    for _ in range(iterations // 2 + 1):
        payload = {
            "ticket_description": "The user interface is loading very slowly. When checking browser developer tools, the API request to retrieve active tickets takes over 5 seconds."
        }
        await client.post("/ai/summarize", json=payload)

    print(f"[5/5] Cleaning up / deleting {len(created_ticket_ids)} tickets...")
    # Deletes
    for tid in created_ticket_ids:
        await client.delete(f"/tickets/ticket/{tid}")


def print_results(profiler: cProfile.Profile, prof_file: str, summary_file: str):
    """Saves profiling statistics and prints a console summary."""
    # Write binary profile data
    profiler.dump_stats(prof_file)
    print(f"\n[+] Raw profiling database dump saved to: {prof_file}")

    # Generate text summary report
    s = io.StringIO()
    s.write("=" * 80 + "\n")
    s.write("                      AI SERVICE DESK PERFORMANCE PROFILE\n")
    s.write("=" * 80 + "\n\n")

    # Cumulative time report
    s.write("TOP 40 FUNCTIONS SORTED BY CUMULATIVE TIME (Wall time/Event Loop overhead):\n")
    s.write("-" * 80 + "\n")
    ps_cum = pstats.Stats(profiler, stream=s).sort_stats("cumulative")
    ps_cum.print_stats(40)

    # Internal CPU time report
    s.write("\n" + "=" * 80 + "\n")
    s.write("TOP 40 FUNCTIONS SORTED BY INTERNAL CPU TIME (Actual execution hotspots):\n")
    s.write("-" * 80 + "\n")
    ps_tot = pstats.Stats(profiler, stream=s).sort_stats("tottime")
    ps_tot.print_stats(40)

    with open(summary_file, "w", encoding="utf-8") as f:
        f.write(s.getvalue())

    print(f"[+] Human-readable summary analysis saved to: {summary_file}")

    # Output a concise preview to the terminal
    print("\n" + "-" * 40 + " Top 10 CPU Hotspots (Internal Execution Time) " + "-" * 40)
    pstats.Stats(profiler).sort_stats("tottime").print_stats(10)


async def main():
    parser = argparse.ArgumentParser(description="Profile Test Runner for FastAPI Ticket Service Desk")
    parser.add_argument(
        "--database",
        choices=["postgres", "sqlite", "auto"],
        default="auto",
        help="Database engine to use (auto: try postgresql, fallback to SQLite if offline)"
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=50,
        help="Number of tickets to create and process during profiling workflow (default: 50)"
    )
    parser.add_argument(
        "--prof-file",
        default="app_profile.prof",
        help="Filename to save the raw cProfile binary stats (default: app_profile.prof)"
    )
    parser.add_argument(
        "--summary-file",
        default="profile_summary.txt",
        help="Filename to save the human-readable text analysis (default: profile_summary.txt)"
    )
    args = parser.parse_args()

    # Determine database selection
    db_choice = args.database
    engine = None

    if db_choice in ("postgres", "auto"):
        print("[*] Testing PostgreSQL connection...")
        if await check_postgres():
            print("[+] PostgreSQL is online and reachable. Using PostgreSQL.")
            engine = pg_engine
        else:
            print("[-] PostgreSQL connection failed/offline.")
            if db_choice == "postgres":
                print("[ERROR] PostgreSQL was explicitly requested, but cannot be reached. Exiting.")
                sys.exit(1)

    if engine is None:
        # We need to fall back to SQLite
        try:
            import aiosqlite
        except ImportError:
            print("\n[CRITICAL ERROR] SQLite fallback is required but 'aiosqlite' is not installed.")
            print("To run profile testing, please either:")
            print("  1. Start your local PostgreSQL server (configured in your .env / .env.test file)")
            print("  2. Install aiosqlite for an in-memory SQL database: 'uv pip install aiosqlite'\n")
            sys.exit(1)

        print("[!] Using SQLite fallback (in-memory db with shared cache).")
        # StaticPool keeps the single in-memory SQLite connection open so metadata/tables persist
        engine = create_async_engine(
            "sqlite+aiosqlite:///file:memdb_profile?mode=memory&cache=shared",
            poolclass=StaticPool,
            echo=False
        )

        # Override the FastAPI db session dependency to use SQLite
        sqlite_session_local = async_sessionmaker(bind=engine, class_=AsyncSession, expire_on_commit=False)
        
        async def override_get_db():
            async with sqlite_session_local() as session:
                try:
                    yield session
                    await session.commit()
                except Exception:
                    await session.rollback()
                    raise
                    
        app.dependency_overrides[get_db] = override_get_db

    # Initialize tables
    print("[*] Initializing database schema...")
    try:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.drop_all)
            await conn.run_sync(Base.metadata.create_all)
        print("[+] Schema initialized successfully.")
    except Exception as e:
        print(f"[CRITICAL ERROR] Failed to initialize DB schema: {e}")
        sys.exit(1)

    # Set up client and run with profiler
    async def run_scenario():
        async with AsyncClient(
            transport=ASGITransport(app=app),
            base_url="http://test"
        ) as client:
            await run_profiling_scenario(client, args.iterations)

    print("\n[*] Starting execution profiling...")
    profiler = cProfile.Profile()
    profiler.enable()

    try:
        await run_scenario()
    finally:
        profiler.disable()
        # Clean up database tables
        print("[*] Cleaning up database schema...")
        try:
            async with engine.begin() as conn:
                await conn.run_sync(Base.metadata.drop_all)
        except Exception:
            pass

    # Print results
    print_results(profiler, args.prof_file, args.summary_file)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n[!] Profiling execution cancelled by user.")
