"""added description column for bedrock to update 

Revision ID: 271af0a9fd36
Revises: 995afac0466e
Create Date: 2026-07-24 00:17:35.736490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271af0a9fd36'
down_revision: Union[str, Sequence[str], None] = '995afac0466e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('description', sa.String(), nullable=True))
    op.execute("UPDATE ticket SET description = 'No description provided' WHERE description IS NULL")
    op.alter_column('ticket', 'description', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'description')
    # ### end Alembic commands ###
