"""add_assignee_email

Revision ID: 435be600d120
Revises: 8ef0bace69ea
Create Date: 2026-07-21 22:56:12.019345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435be600d120'
down_revision: Union[str, Sequence[str], None] = '8ef0bace69ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('assignee_email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'assignee_email')
    # ### end Alembic commands ###
